name: kuberadmsdn
description: "LHC DMS Mobile Application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # 📷 Camera
  camera: ^0.11.3+7

  # 🔐 Storage
  shared_preferences: ^2.2.2

  # 🌐 Networking
  http: ^1.1.0
  dio: ^5.4.0

  # 📅 Formatting
  intl: ^0.20.2

  # 📷 Media
  image_picker: ^1.0.4

  # 📍 Location
  geolocator: ^12.0.0
  permission_handler: ^12.0.1

  # 🗺️ OpenStreetMap
  flutter_map: ^8.2.1
  latlong2: ^0.9.1
  url_launcher: ^6.3.2

  # 📱 Device Info
  device_info_plus: ^12.3.0

  # 🖼 UI
  cupertino_icons: ^1.0.8

  # 📄 PDF & Printing
  pdf: ^3.11.3
  printing: ^5.14.2

  # 📸 Screenshot
  screenshot: ^3.0.0

  # 💾 Save image/PDF to gallery
  gal: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # 🚀 App Icon Generator
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/logo.jpg

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.jpg"

  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/logo.jpg"