name: kuberadmsdn
description: "LHC DMS Mobile Application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  shared_preferences: ^2.2.2
  http: ^1.1.0
  intl: ^0.18.1   # <-- add this line
  image_picker: ^1.0.4
  geolocator: ^10.1.0
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  device_info_plus: ^10.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "#FFFFFF"